# telegram_webhook_bot.py
import os
from flask import Flask, request
import telebot
import yt_dlp
import tempfile

# 1️⃣ Telegram token
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
if not TELEGRAM_TOKEN:
    raise RuntimeError("TELEGRAM_TOKEN aniqlanmadi!")

bot = telebot.TeleBot(TELEGRAM_TOKEN)
app = Flask(__name__)

# 2️⃣ Cookie matni — shu yerga sizning cookies.txt ichidagi ma’lumotni joylang
INSTAGRAM_COOKIE = """
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.
"""  # ⬆ bu joyga brauzerdan eksport qilingan cookie yoziladi

# 3️⃣ Start / help buyrug‘i
@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    markup = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
    markup.add("🎥 Video yuklash", "📩 Admin bilan aloqa", "🎨 Rasm yasash")
    bot.send_message(
        message.chat.id,
        "Assalomu alaykum!\nPastdagi tugmalardan birini tanlang:",
        reply_markup=markup
    )

# 4️⃣ Tugma tanlanganda
@bot.message_handler(func=lambda message: message.text == "📩 Admin bilan aloqa")
def contact_admin(message):
    bot.reply_to(message, "Admin bilan aloqa uchun: @Asqarov_0207")

@bot.message_handler(func=lambda message: message.text == "🎨 Rasm yasash")
def make_image(message):
    bot.reply_to(message, "✍️ Rasm yaratish xizmati hozircha sinovda — tez orada qo‘shiladi!")

@bot.message_handler(func=lambda message: message.text == "🎥 Video yuklash")
def ask_video_link(message):
    bot.reply_to(message, "🎥 Video havolasini yuboring (Instagram, YouTube va boshqalar).")

# 5️⃣ Video link kelganda yuklab berish
@bot.message_handler(func=lambda message: message.text.startswith("http"))
def download_video(message):
    url = message.text.strip()
    bot.reply_to(message, "⏳ Yuklab olinmoqda...")

    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            ydl_opts = {
                'outtmpl': f'{tmpdir}/%(title)s.%(ext)s',
                'cookiefile': 'cookies.txt' if INSTAGRAM_COOKIE.strip() else None,
            }
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=True)
                video_path = ydl.prepare_filename(info)

            with open(video_path, 'rb') as video:
                bot.send_video(message.chat.id, video)

    except Exception as e:
        bot.reply_to(message, f"❌ Xatolik: {e}")

# 6️⃣ Flask webhook yo‘li
@app.route(f'/{TELEGRAM_TOKEN}', methods=['POST'])
def receive_update():
    json_str = request.get_data().decode('utf-8')
    update = telebot.types.Update.de_json(json_str)
    bot.process_new_updates([update])
    return "OK", 200

# 7️⃣ Asosiy ishga tushirish
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)
